spring:
  application:
    name: lovable-clone
    description: this is application

  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8082

jwt:
  secret-key : uqefuiew873274983yr9287gf8273293usiwejhfoiregniwbeyewyydwg98d298347234732bhjduwdcdjshc

stripe:
  api:
    secret: sk_test_51StlckSAuIds6r3FnWxsY0UMOcuU5PXWVwR8bwy29u06iiR728Qh5xdw05OTegpx3f1EpD8HZWFLgUL4oDBirz9j00CyT9xdxR
  webhook:
    secret: whsec_f39e12e405e46e64210a9b207e0589a5dd73bedf43c50ae8c573f1468c4dedac
client.url: http://localhost:8082  #for after payment rediection (usually has to be frontend url)

